ui: ui_mainwindow.py ui_pairwindow.py ui_optionwidget.py


ui_mainwindow.py: mainwindow.ui
	pyuic5 -o $@ $<
	
ui_pairwindow.py: pairwindow.ui
	pyuic5 -o $@ $<
	
ui_optionwidget.py: optionwidget.ui
	pyuic5 -o $@ $<

